#Mon May 19 09:47:57 CEST 2025
micronaut:
  application:
    name: bakery-stock
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        mapping: /swagger-ui/**
        paths: classpath:META-INF/swagger/views/swagger-ui
  openapi:
    property:
      naming:
        strategy: SNAKE_CASE
